<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

# vim:tabstop=2:softtabstop=2:shiftwidth=2:noexpandtab:e 
# Process the command line parameters

if(file_exists(BASE_PATH."/core/configs/slideatlas.local.ini"))
  {
  $applicationConfig = parse_ini_file(BASE_PATH."/core/configs/slideatlas.local.ini", true);
  }
else
  {
  $applicationConfig = parse_ini_file(BASE_PATH.'/modules/slideatlas/configs/module.ini', true);
  } 
$server = $applicationConfig['global']['mongoserver'];
$database = $applicationConfig['global']['dbname'];


@$col_name =  $this->image;
@$fname =     $this->name;

//header('content-type: image/jpeg');
# Return grey image as there is error or parameters not set
header('content-type: image/jpeg');
function grey_out($tilesize)
	{
	#header('content-type: image/jpeg');
	$im = file_get_contents(BASE_PATH."/modules/slideatlas/public/images/blank-".$tilesize.".jpg");
	echo $im; 
	}

# If parameters not available
if(!isset($col_name) || !isset($fname))
  {
	grey_out($this->tilesize);
	return;
  }
try
	{
	# Connect
	$m = new Mongo($server);
	$collection = $m->selectDB($database)->selectCollection($col_name);
	
	# Query 
	$cursor = $collection->findOne( array('name' => $fname));
	if($cursor == null)
		{
		throw new Exception('Image not in database');
		}
	# Return the image chunk 
	$im = $cursor['file'];
	echo $im->bin;
	}
	catch(Exception $e)
	{
	grey_out($this->tilesize);
	}
?>
