<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

echo $this->doctype();
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>  
  <title> <?php echo $this->title ?> </title>
  <link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/user/user.fullscreen.css" />
</head>

<body >  
  <div id="mapcontainer">
    <div id="map"></div>
    <div id="operations">
		  <div id="plus" class='largeImageButton' onclick="midas.slideatlas.user.zoom2(1);">
        <img id="uploadAFile" src="<?php echo $this->moduleWebroot?>/public/images/zoom-in.png" alt="zoom in"/>
      </div>  
		  <div id="minus" class='largeImageButton' onclick="midas.slideatlas.user.zoom2(-1);">
        <img id="uploadAFile" src="<?php echo $this->moduleWebroot?>/public/images/zoom-out.png" alt="zoom out"/>
      </div>
		  <div id="rotatel" class='largeImageButton' onclick="midas.slideatlas.user.rotate2(5);">
        <img id="uploadAFile" src="<?php echo $this->moduleWebroot?>/public/images/rotate-right.png" alt="rotate right"/>
      </div>
		  <div id="rotater" class='largeImageButton' onclick="midas.slideatlas.user.rotate2(-5);">
        <img id="uploadAFile" src="<?php echo $this->moduleWebroot?>/public/images/rotate-left.png" alt="rotate left"/>
      </div>
    </div>
  </div>
	
<div style="display: none;" class="jsonContent">
  <?php echo $this->json?>
</div>

<?php
  echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.js"></script>';
  echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/viewer/css-transform.js"></script>';
  echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/viewer/css-rotate.js"></script>';
  echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/viewer/OpenLayers.mobile.js"></script>';
  echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/user/user.fullscreen.js"></script>';
?>  
</body>
</html>
