<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

echo $this->doctype();
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>  
  <title> Rotated full screen digital pathology view </title>
  <link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/user/user.fullscreen.css" />
</head>

<body >  
  <div id="mapcontainer">
    <div id="map"></div>
		<div id="plus" class='button' onclick="midas.slideatlas.user.zoom2(1);"> Zoom In </div>
		<div id="minus" class='button' onclick="midas.slideatlas.user.zoom2(-1);"> Zoom Out </div>
		<div id="rotatel" class='button' onclick="midas.slideatlas.user.rotate(5);"> Rotate Right </div>
		<div id="rotater" class='button' onclick="midas.slideatlas.user.rotate(-5);"> Rotate Left </div>
  </div>
	
<div style="display: none;" class="jsonContent">
  <?php echo $this->json?>
</div>

<?php
  echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.js"></script>';
  echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/viewer/css-transform.js"></script>';
  echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/viewer/css-rotate.js"></script>';
  echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/viewer/OpenLayers.mobile.js"></script>';
  echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/user/user.fullscreen.js"></script>';
?>  
</body>
</html>
