<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/element/element.listfiles.css" />

<div class="viewMain">
   <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/user/userpage'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');  
            echo "</a>";
          echo '</div>';
          
        ?>
  </div>   
  <div class="genericThumbnail">
  <?php
  echo $this->userthumbnail($this->user->getThumbnail());
  ?>
  </div>
  <div class="genericInfo">
    <div class="genericName"><?php echo $this->user->getFullName();?></div>
    <div class="genericSubtitle"><?php echo $this->user->getCompany();?>
        <span id="locationUser">
        <?php
        $city = $this->user->getCity();
        $country = $this->user->getCountry();
        if(!empty($city))
          {
          echo $city;
          if(!empty($country))
            {
            echo ', ';
            }
          }
        if(!empty($country))
          {
          echo $country;
          }
          ?>
        </span>
      </div>
  </div>
  <div class="viewHeader">Connectcome Images</div>
  <div class="listimages">
   <?php
    if($this->isViewAction)
      {
      $this->listFiles = $this->ownedItems;
      echo $this->element('listimages');
      }
   ?>
  </div>

</div>




